export const images = {
    house1: "house1.webp",
    house1a: "house1a.webp",
    house1c: "house1c.webp",
    house2: "house2.webp",
    mansion1: "mansion1.webp",
    mansion2: "mansion2.webp",
    mansion2c: "mansion2c.webp",
    npc00: "npc0.webp",
    npc0: "npc0.webp",
    npc1: "npc1.webp",
    npc2: "npc2.webp",
    npc3: "npc3.webp",
    npc4: "npc4.webp",
    npc5: "npc5.webp",
    npc6: "npc6.webp",
    news1a: "news1a.png",
    news1b: "news1b.png",
    news1c: "news1c.png",
    news2a: "news2a.png",
    news2b: "news2b.png",
    news2c: "news2c.png",
    news3a: "news3a.png",
    news3b: "news3b.png",
    news3c: "news3c.png",
    news3d: "news3d.png",
    arvind1: "arvind1.webp",
    arvind2: "arvind2.webp",
    arvind3: "arvind3.webp",
    arvind4: "arvind4.webp",
    sky1: "sky1.webp",
    sky2: "sky2.webp",
    street1: "street1.webp",
    street2: "street2.webp",
    rickshaw: "rickshaw.webp",
    sparkle1: "sparkle1.webp",
    sparkle2: "sparkle2.webp",
    sparkle3: "sparkle3.webp",
    sparkle4: "sparkle4.webp",
    sparkle5: "sparkle5.webp",
    sparkle6: "sparkle6.webp",
    sparkle7: "sparkle7.webp",
};

for (const i in images) {
    const o = new Image();
    o.src = images[i];
    images[i] = o;
}

export const everything = {

    npcs: [
        {
            level: 1,
            sprite: "npc0",
            dialogue: [
                "A / D to move left and right. Enter to interact/talk. Double click or F to view newspapers. [Click], Q, or use number keys to switch newspapers. To deliver a newspaper, select one and interact with a house.",
                "Once you're done, talk to the guy in the white suit to check your answer!",
            ],
            x: 0,
            y: 88,
            w: 30,
            h: 60,
        },
        {
            level: 1,
            sprite: "npc1",
            dialogue: [
                "I'm looking high and low for a Malay translator, but I think I'm at the wrong address..."
            ],
            x: 110,
            y: 95,
            w: 27,
            h: 54,
        },
        {
            level: 1,
            sprite: "npc2",
            dialogue: ["I send a ton of letters to my family back in Germany, but I only have time to write them when it's dark :("],
            x: 580,
            y: 91,
            w: 29,
            h: 58,
            flip: true,
        },
        {
            level: 2,
            sprite: "npc0",
            dialogue: [
                "A / D to move left and right. Enter to interact/talk. Double click or F to view newspapers. [Click], Q, or use number keys to switch newspapers. To deliver a newspaper, select one and interact with a house.",
                "Once you're done, talk to the guy in the white suit to check your answer!",
            ],
            x: 0,
            y: 88,
            w: 30,
            h: 60,
        },
        {
            level: 2,
            sprite: "npc3",
            dialogue: ["I live here now, but I want to visit my family in Australia someday."],
            x: -260,
            y: 91,
            w: 27,
            h: 54,
        },
        {
            level: 2,
            sprite: "npc4",
            dialogue: ["Egads, I can't stand that musician at the end of the street!"],
            x: 350,
            y: 91,
            w: 27,
            h: 54,
        },
        {
            level: 3,
            sprite: "npc0",
            dialogue: [
                "A / D to move left and right. Enter to interact/talk. Double click or F to view newspapers. [Click], Q, or use number keys to switch newspapers. To deliver a newspaper, select one and interact with a house.",
                "Once you're done, talk to the guy in the white suit to check your answer!",
            ],
            x: 150,
            y: 88,
            w: 30,
            h: 60,
        },
        {
            level: 3,
            sprite: "npc5",
            dialogue: ["Must be tough delivering newspapers when no two neighbours read from the same publisher."],
            x: -300,
            y: 91,
            w: 27,
            h: 54,
            flip: true,
        },
        {
            level: 3,
            sprite: "sparkle",
            dialogue: ["A cricket betting slip on the floor. It probably belongs to one of the two neighbouring houses..."],
            x: -115,
            y: 125,
            w: 20,
            h: 20,
        },
        {
            level: 3,
            sprite: "npc6",
            dialogue: ["The two former sailors living on opposite ends of this street meet at the bar every night discussing maritime news."],
            x: 425,
            y: 91,
            w: 27,
            h: 54,
        },
        {
            level: 4,
            sprite: "npc00",
            dialogue: [
                "You have completed the game! To go back to the main menu, interact with the tiny house!",
            ],
            x: 100,
            y: 100,
            w: 30,
            h: 60,
            flip: 2,
        },
        {
            level: 4,
            sprite: "arvind4",
            dialogue: ["Who are you? Why are you so small?"],
            x: 260,
            y: 91,
            w: 50,
            h: 100,
        },
    ],

    houses: [
        {
            level: 1,
            sprite: "house1",
            map: 1,
            x: -110,
            y: 19,
            w: 200,
            h: 200,
            ans: 1,
        },
        {
            level: 1,
            sprite: "mansion1",
            map: 2,
            x: 210,
            y: -42,
            w: 320,
            h: 320,
            ans: 2,
        },
        {
            level: 1,
            sprite: "house1a",
            map: 1,
            x: 510,
            y: 19,
            w: 200,
            h: 200,
            ans: 0,
        },
        {
            level: 2,
            sprite: "house1c",
            map: 1,
            x: -210,
            y: 19,
            w: 200,
            h: 200,
            ans: 3,
        },
        {
            level: 2,
            sprite: "mansion2c",
            map: 0,
            x: 110,
            y: -42,
            w: 320,
            h: 320,
            ans: 5,
        },
        {
            level: 2,
            sprite: "house2",
            map: 0,
            x: 440,
            y: 19,
            w: 200,
            h: 200,
            ans: -1,
        },
        {
            level: 2,
            sprite: "house1c",
            map: 1,
            x: 660,
            y: 19,
            w: 200,
            h: 200,
            ans: 4,
        },
        {
            level: 3,
            sprite: "house2",
            map: 0,
            x: -210,
            y: 19,
            w: 200,
            h: 200,
            ans: 9,
        },
        {
            level: 3,
            sprite: "house1",
            map: 1,
            x: -26,
            y: 19,
            w: 200,
            h: 200,
            ans: 7,
        },
        {
            level: 3,
            sprite: "mansion1",
            map: 2,
            x: 250,
            y: -42,
            w: 320,
            h: 320,
            ans: 8,
        },
        {
            level: 3,
            sprite: "mansion2",
            map: 0,
            x: 600,
            y: -31,
            w: 300,
            h: 300,
            ans: 6,
        },
        {
            level: 4,
            sprite: "house1a",
            map: 0,
            x: -100,
            y: 95,
            w: 50,
            h: 50,
            ans: -1,
            flip: true,
        },
        {
            level: 4,
            sprite: "mansion1",
            x: 100,
            y: 280,
            w: 250,
            h: 250,
            ans: 8,
            flip: 2,
        },
        {
            level: 4,
            sprite: "house1c",
            x: 500,
            y: 230,
            w: 160,
            h: 160,
            ans: 8,
            flip: 2,
        },
    ],

    papers: [
        {
            level: 1,
            image: "news1a",
            headline: "Arvind spotted without green tea",
            text: "on the green line",
            x: -200,
        },
        {
            level: 1,
            image: "news1b",
            x: 190,
        },
        {
            level: 1,
            image: "news1c",
            x: 500,
        },
        {
            level: 2,
            image: "news2a",
            x: -140,
            // y: 40,
        },
        {
            level: 2,
            image: "news2b",
            x: 160,
            // y: 40,
        },
        {
            level: 2,
            image: "news2c",
            x: 350,
        },
        {
            level: 3,
            image: "news3a",
            x: -200,
        },
        {
            level: 3,
            image: "news3b",
            x: 150,
        },
        {
            level: 3,
            image: "news3c",
            x: 300,
        },
        {
            level: 3,
            image: "news3d",
            x: 500,
        },
    ],

    boxes: [
        // left and right walls
        {
            x: -400,
            y: 1000,
            h: 17120,
            c: "transparent",
        },
        {
            x: 800,
            y: 1000,
            h: 17120,
            c: "transparent",
        },
        // level 1 floor
        {
            level: 1,
            x: 0,
            y: 150,
            w: 10000,
            h: 45,
            c: "transparent",
        },
        // level 2 floor
        {
            level: 2,
            x: 0,
            y: 150,
            w: 10000,
            h: 45,
            c: "transparent",
        },
        { // i forgot what this was
            level: 2,
            x: -150,
            y: 53,
            w: 10,
            h: 5,
            c: "transparent",
        },
        // level 3 floor
        {
            level: 3,
            x: 0,
            y: 150,
            w: 10000,
            h: 45,
            c: "transparent",
        },
        // level 4 floor
        {
            level: 4,
            x: 0,
            y: 150,
            w: 10000,
            h: 45,
            c: "transparent",
        },
        {
            level: 4,
            x: -100,
            y: 75,
            w: 30,
            h: 5,
            c: "transparent",
        },
        {
            level: 4,
            x: 100,
            y: 73,
            w: 20,
            h: 5,
            c: "transparent",
        },
        {
            level: 4,
            x: 255,
            y: 43,
            w: 25,
            h: 5,
            c: "fuchsia",
        },
        {
            level: 4,
            x: 400,
            y: 70,
            w: 30,
            h: 5,
            c: "fuchsia",
        },
    ],

    decoration: [
        { // level 1 floor
            level: 1,
            x: 0,
            y: 140,
            w: 5000,
            h: 45,
            c: "coral",
        },
        {
            level: 1,
            x: -250,
            y: 35,
            w: 200,
            h: 200,
            sprite: "rickshaw",
        },
        { // level 2 floor
            level: 2,
            x: 0,
            y: 140,
            w: 5000,
            h: 45,
            c: "coral",
        },
        { // level 3 floor
            level: 3,
            x: 0,
            y: 140,
            w: 5000,
            h: 45,
            c: "coral",
        },
        { // level 4 floor
            level: 4,
            x: 0,
            y: 140,
            w: 5000,
            h: 45,
            c: "coral",
        },

    ],
};

for (const h of everything.houses) {
    let add = [];
    if (h.map === 1) {
        add = [{
            x: 0,
            y: -71,
            w: 135,
            h: 5,
            c: "transparent",
        }, {
            x: -40,
            y: 53,
            w: 10,
            h: 5,
            c: "transparent",
        }, {
            x: -40,
            y: 84,
            w: 10,
            h: 5,
            c: "transparent",
        }, {
            x: -25,
            y: 81,
            w: 10,
            h: 5,
            c: "transparent",
        }, {
            x: -26,
            y: 59,
            w: 8,
            h: 5,
            c: "transparent",
        }];
    }
    else if (h.map === 2) {
        add = [
            {
                x: 100,
                y: 100,
                w: 40,
                h: 5,
                c: "transparent",
            }, {
                x: 0,
                y: 10,
                w: 310,
                h: 5,
                c: "transparent",
            }, {
                x: 0,
                y: -20,
                w: 110,
                h: 5,
                c: "transparent",
            }, {
                x: -110,
                y: -10,
                w: 90,
                h: 5,
                c: "transparent",
            }, {
                x: 110,
                y: -10,
                w: 90,
                h: 5,
                c: "transparent",
            }, {
                x: -110,
                y: -129,
                w: 70,
                h: 5,
                c: "transparent",
            }, {
                x: 110,
                y: -129,
                w: 70,
                h: 5,
                c: "transparent",
            },
        ];
        for (let i = 0; i < 12; i++) {
            add.push({
                x: 0,
                y: -110 - i * 5,
                w: 120 - i * 10,
                h: 5,
                c: "transparent",
            });
        }
    }
    for (const a of add) {
        a.x += h.x;
        a.level = h.level;
        everything.boxes.push(a);
    }
}